### ISSUE TITLE
Crash when setting tail crop

### ISSUE THREAD

**Issue by mbassalbioinformatics** [hellosunking/Msuite2#4]
Hi

when attempting to run msuite2 with the following flags (--cut-r1-tail 100 --cut-r2-tail 100), it keeps crashing immediately with the following

```
Loading files ...
INFO: 1 paired fastq files will be loaded.
terminate called after throwing an instance of 'std::length_error'
terminate called recursively
  what():  basic_string::_M_replace_aux
make: *** [makefile:6: Msuite2.trim.log] Aborted (core dumped)
```

any suggestions/ideas whats causing the crash??

**Comment by hellosunking** [comment]
Hi,

This error is because your parameter is too large. By default, Msuite2 will keep reads larger than 36 bp for trimming tails,
therefore some short reads, say 50 bp, do not have 100 bp tail to trim.
I suggest you decrease the parameter (e.g., reduce to 10). If this parameter can not be changed, you can set the "--minsize"
parameter to a larger number (e.g., 136, which must be larger than your trim parameter).

Regards,
Kun

**Comment by mbassalbioinformatics** [comment]
ok so the number you give to msuite is the number of cycles from the end of the read. So say i have reads of 150bp and i want to trim to 130bp, then i put the tail trim to 20 and not 130, right?
